### ISSUE TITLE
Find broken block references and invalid section

### ISSUE THREAD

**Issue by HelloHumans13** [Vinzent03/find-unlinked-files#50] opened 2023-08-01 14:14 UTC
When I delete an internal link, the block identifiers isn't updated. Also I would like to find links with invalid section.

**Comment by Vinzent03** [comment] 2023-08-09 09:40
Please describe more in detail what you want. Do you want links to non existing heading and/or blocks, or find block ids that are no longer linked to?

**Comment by HelloHumans13** [comment] 2023-08-10 15:20
I want to find and delete links to non existing heading/blocks and block ids that are no longer linked.

**Comment by jvdevlab** [comment] 2024-01-03 01:14
Seems to be a dupe of https://github.com/Vinzent03/find-unlinked-files/issues/36 (maybe upvote there)

**Closed** 2024-01-16 14:21 UTC
Labels: enhancement
